spring:
  application:
    name: william278-backend

  # Stop the serving of static resources
  web:
    resources:
      add-mappings: false

  # Configure the database
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configure Discord OAuth2
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_CLIENT_SECRET}
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope:
              - identify
            redirect-uri: '{baseUrl}/login'
            clientName: 'William278.net backend'
        provider:
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username

# Provide OpenAPI docs
springdoc:
  show-actuator: false
  api-docs:
    path: "/openapi"
  swagger-ui:
    disable-swagger-default-url: true
    show-common-extensions: true
    operations-sorter: "alpha"
    path: "/docs/"

# Hides the Whitelabel error page
server:
  error:
    whitelabel:
      enabled: false